baseURL: https://hanyu-wang-website.netlify.app/
languageCode: en-us
title: Portfolios for Hanyu Wang
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      DEVELOP MYSELF AS A PRODUCT.
    title: Hi, I'm 王涵宇. Just call me Hovik :)
  blog: {}
  contact:
    address:
      - city: London, W1H 2LH
        country: United Kingdom
        street: Montagu Square
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: hwang.mam2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (44) 07536970456
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: London Business School
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com/Nullboi2
      #- icon: fa-facebook
        #label: Facebook
        #url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/nullboi_/
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/nullboi
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/hanyuwangmam2022/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    #button2:
      #- name: Log In
        #url: '#'
    links:
      - name: Home
        url: '#'
      - name: LinkedIn
        url: https://www.linkedin.com/in/hanyuwangmam2022/
      #- name: Generic Blog
        #url: blogs/ipsum
      #- name: Elements
        #url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: self.jpeg
        subtitle: Billingual interview about my UG Career
        title: Know more about Me
        url: https://mp.weixin.qq.com/s/AL-zTh7pdJTtFPLabYSLBw
      - image: tie.jpg
        subtitle: Build up our career contacts
        title: Resume
        url: blogs/HanyuWang_resume.pdf
      - image: pic09.jpg
        subtitle: Pre-program coursework
        title: My work
        url: blogs/hanyuwang
      - image: beer.jpg
        subtitle: First chanllenge
        title: First R Group Project
        url: blogs/hwfirst
      - image: pic08.jpg
        subtitle: Contact me on Github
        title: Technology communication
        url: https://www.github.com/nullboi
      - image: LBS.jpeg
        subtitle: Walk around London business school
        title: My campus
        url: http://london.edu

  #two:
    #buttonText: Get Started
    #enable: yes
    #subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      #\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      #condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      #pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      #Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      #amet pharetra et feugiat tempus."
    #title: Massa libero
    #url: blogs
